---
:concurrency: 5
:timeout: 25
:verbose: true
:queues:
  - default
  - mailers

:schedule:
  daily_blocker_email:
    cron: '30 10 * * *'
    class: 'DailyBlockerJob'
    queue: default
    active_job: true
    description: 'Send daily blocker summary email to manager'