source "https://rubygems.org"

gem "rails", "~> 8.1.2"
gem "propshaft"
# gem "sqlite3", ">= 2.1"
gem "pg"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "table_print"
gem "rspec-rails"
gem "rack-cors"
gem "faker", "~>3.2"
gem "redis", "~> 5.0"
gem "connection_pool", "~> 2.4"
gem "good_job", "~> 4.6"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "dotenv-rails", groups: [ :development, :test ]

gem "solid_cache"
gem "solid_cable"

gem "grape"
gem "grape-entity"

gem "bootsnap", require: false

gem "kamal", require: false

gem "thruster", require: false

gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ], require: "debug/prelude"

  gem "bundler-audit", require: false

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

gem "devise", "~> 5.0"
